version: '3.1'

networks:
  docker:

volumes:
  jenkins-data:
  jenkins-docker-certs:

services:

  # Docker-in-Docker (DinD) Service
  dind:
    image: docker:dind  # Docker-in-Docker image
    privileged: true  # Allows running Docker inside Docker
    restart: always  # Always restart the container if it stops
    networks:
      docker:
        aliases: 
          - docker  # This gives the service an alias "docker" on the network
    ports:
      - 2376:2376  # Exposing the Docker daemon port (2376)
    tty: true  # Allocate a pseudo-TTY
    volumes:
      - jenkins-data:/var/jenkins_home  # Persist Jenkins data
      - jenkins-docker-certs:/certs/client  # Certificates for Docker communication
      - /var/run/docker.sock:/var/run/docker.sock  # Mounting the Docker socket for host communication
    environment:
      - DOCKER_TLS_CERTDIR=/certs  # Enable TLS certificates

  # Jenkins Service
  jenkins:
    image: jenkins/jenkins:lts  # Latest Long-Term Support version of Jenkins
    restart: always  # Automatically restart if the container crashes
    networks:
      - docker  # Same network as DinD to enable communication
    ports:
      - 8080:8080  # Expose Jenkins UI port
      - 50000:50000  # Expose Jenkins agent port
    tty: true  # Allocate a pseudo-TTY
    volumes:
      - jenkins-data:/var/jenkins_home  # Persist Jenkins data
      - jenkins-docker-certs:/certs/client:ro  # Certificates for Docker
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket mount for host communication
    environment:
      - DOCKER_HOST=tcp://docker:2376  # DinD as Docker host
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
